# Generated by Django 5.2.4 on 2025-07-27 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(help_text='Unique part number for the product.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the product.')),
                ('current_stock', models.IntegerField(default=0, help_text='The current available stock for this product.')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['part_no'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(help_text='A unique code for the transaction (e.g., GRN-001, DO-001).', max_length=20, unique=True)),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], help_text='The type of transaction (IN or OUT).', max_length=3)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time of the transaction.')),
                ('notes', models.TextField(blank=True, help_text='Any notes related to the transaction.', null=True)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='The quantity of the product for this transaction line.')),
                ('product', models.ForeignKey(help_text='The product involved in this transaction line.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
                ('transaction', models.ForeignKey(help_text='The parent transaction for this detail line.', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.stocktransaction')),
            ],
            options={
                'verbose_name': 'Stock Transaction Detail',
                'verbose_name_plural': 'Stock Transaction Details',
                'unique_together': {('transaction', 'product')},
            },
        ),
    ]
